// tempo_languages.js
window.i18nData = {
    en: {
        back_to_list: "Back to List",
        full_catalog: "Complete catalog of all links and activities",
        login: "Login",
        sync_progress: "Sync your progress with the cloud",
        data_synced: "Data synced",
        logout: "Logout",
        light_theme: "Light Theme",
        dark_theme: "Dark Theme",
        light_theme_active: "Light theme active",
        dark_theme_active: "Dark theme active",
        hide_badges: "Hide Badges",
        show_badges: "Show Badges",
        badges_shown: "Badges shown",
        badges_hidden: "Badges hidden",
        edit_mode: "Edit Mode",
        finish_editing: "Finish",
        edit_mode_activated: "Edit mode activated",
        edit_mode_finished: "Edit mode finished",
        edit_mode_banner: "Edit Mode — click ✎ next to a link to modify",
        start_editing: "Start editing",
        export_json: "Export JSON",
        import_json: "Import JSON",
        upload_github: "Upload to GitHub",
        reset_progress: "Reset Progress",
        how_tracking_works: "How Tracking Works",
        hide_legend: "Hide ▾",
        show_legend: "Show ▸",
        today: "Today",
        today_desc: "Green color — action done today. After midnight the mark disappears.",
        done: "Done",
        done_desc: "Strikethrough — one-time task is closed.",
        clicks_date_desc: "Number of clicks and date.",
        new_indicator: "NEW!",
        new_desc: "Fresh links. After click the mark disappears.",
        favorites: "Favorites",
        no_favorites: "No favorite links. Click ★ next to needed ones.",
        section_faucets: "1. Get Test Tokens (Tempo Faucet)",
        section_deploy: "2. Deploy Smart Contracts",
        section_nfts: "3. Mint NFT (All Collections)",
        section_dapps: "4. dApps and Activities",
        faucets_note: "If faucet doesn't open, try VPN or refresh page.",
        basic_deploy: "Basic Deploy",
        advanced_deploy: "Advanced Deploy",
        nfts_note: "Below are direct mint links. Click to mark as completed.",
        bridges: "Bridges",
        bridges_desc: "Send tokens to and from the network.",
        domains: "Domains",
        domains_desc: "Register domains.",
        nft_dapps: "NFT dApps",
        nft_dapps_desc: "Marketplaces and tools.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Daily transactions.",
        quests: "Quests",
        quests_desc: "Complete Layer3 quests.",
        footer_disclaimer: "This site is an aggregator of links. DYOR.",
        data_exported: "Data exported!",
        data_imported: "Data imported!",
        error_import: "Import error",
        progress_reset: "Progress reset",
        element_added: "Element added and synced",
        element_updated: "Element updated and synced",
        go_to_mint: "Go to Mint",
        go_to_website: "Go to Website",
        new_nfts: "New NFTs",
        checking: "Checking...",
        refresh: "Refresh",
        no_new_posts: "No new posts yet",
        add_item: "Add Item",
        title_label: "Title",
        url_label: "URL Link",
        tooltip_label: "Description (tooltip)",
        image_label: "Image URL (for NFT)",
        website_label: "Project Website URL",
        twitter_label: "Project Twitter URL",
        description_label: "Action Description",
        cancel: "Cancel",
        add: "Add",
        save: "Save",
        confirm_delete: "Are you sure you want to delete?",
        delete_item: "Delete item",
        delete_collection: "Delete collection",
        delete_category: "Delete category",
        removed: "Removed",
        collection_created: "Collection created and synced",
        category_created: "Category created and synced",
        group_created: "Group created and synced",
        collection_removed: "Collection removed",
        category_removed: "Category removed",
        add_to: "Add to",
        add_nft: "Add NFT",
        new_elements_updated: "NEW elements updated in real time",
        new_indicator_synced: "NEW indicator synced",
        error_adding_indicator: "Error adding NEW indicator",
        login_title: "Login to System",
        login_google: "Login with Google",
        login_twitter: "Login with Twitter",
        register: "Register",
        login_btn: "Login",
        category: "Category",
        all_links: "All Links",
        action: "Action"
    },
    ru: {
        back_to_list: "Назад к списку",
        full_catalog: "Полный каталог всех ссылок и активностей",
        login: "Войти",
        sync_progress: "Синхронизируйте прогресс с облаком",
        data_synced: "Данные синхронизированы",
        logout: "Выйти",
        light_theme: "Светлая тема",
        dark_theme: "Тёмная тема",
        light_theme_active: "Светлая тема активна",
        dark_theme_active: "Тёмная тема активна",
        hide_badges: "Скрыть бейджи",
        show_badges: "Показать бейджи",
        badges_shown: "Бейджи показаны",
        badges_hidden: "Бейджи скрыты",
        edit_mode: "Режим редактирования",
        finish_editing: "Завершить",
        edit_mode_activated: "Режим редактирования активирован",
        edit_mode_finished: "Режим редактирования завершён",
        edit_mode_banner: "Режим редактирования — нажмите ✎ рядом со ссылкой для изменения",
        start_editing: "Начать редактирование",
        export_json: "Экспорт JSON",
        import_json: "Импорт JSON",
        upload_github: "Загрузить на GitHub",
        reset_progress: "Сбросить прогресс",
        how_tracking_works: "Как работает отслеживание",
        hide_legend: "Скрыть ▾",
        show_legend: "Показать ▸",
        today: "Сегодня",
        today_desc: "Зелёный цвет — действие выполнено сегодня. После полуночи отметка исчезает.",
        done: "Выполнено",
        done_desc: "Зачёркнуто — одноразовая задача закрыта.",
        clicks_date_desc: "Количество кликов и дата последнего действия.",
        new_indicator: "NEW!",
        new_desc: "Свежие ссылки. После клика метка пропадёт.",
        favorites: "Избранное",
        no_favorites: "Нет избранных ссылок. Нажмите ★ рядом с нужными.",
        section_faucets: "1. Получение тестовых токенов (Tempo Faucet)",
        section_deploy: "2. Деплой смарт-контрактов",
        section_nfts: "3. Минт NFT (Все коллекции)",
        section_dapps: "4. dApps и Активности",
        faucets_note: "Если кран не открывается, попробуйте VPN или обновите страницу.",
        basic_deploy: "Базовый деплой",
        advanced_deploy: "Продвинутый деплой",
        nfts_note: "Ниже — прямые ссылки на минт. Нажмите, чтобы отметить выполненное.",
        bridges: "Мосты",
        bridges_desc: "Отправляйте токены в сеть Tempo и обратно.",
        domains: "Domains",
        domains_desc: "Зарегистрируйте домен в сети Tempo.",
        nft_dapps: "NFT",
        nft_dapps_desc: "Создание собственных коллекций.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Ежедневные транзакции «GM», «Check-In», «Vote».",
        quests: "Quests",
        quests_desc: "Выполняем квесты Layer3 по сети Tempo.",
        footer_disclaimer: "Данный сайт является агрегатором ссылок. DYOR.",
        data_exported: "Данные экспортированы!",
        data_imported: "Данные импортированы!",
        error_import: "Ошибка импорта",
        progress_reset: "Прогресс сброшен",
        element_added: "Элемент добавлен и синхронизирован",
        element_updated: "Элемент обновлён и синхронизирован",
        go_to_mint: "Перейти к минту",
        go_to_website: "Перейти на Website",
        new_nfts: "Новые NFT",
        checking: "Проверка...",
        refresh: "Обновить",
        no_new_posts: "Новых постов пока нет",
        add_item: "Добавить элемент",
        title_label: "Название",
        url_label: "URL ссылки",
        tooltip_label: "Описание (tooltip)",
        image_label: "URL картинки (для NFT)",
        website_label: "URL сайта проекта",
        twitter_label: "URL Twitter проекта",
        description_label: "Описание действия",
        cancel: "Отмена",
        add: "Добавить",
        save: "Сохранить",
        confirm_delete: "Вы уверены, что хотите удалить?",
        delete_item: "Удалить элемент",
        delete_collection: "Удалить коллекцию",
        delete_category: "Удалить категорию",
        removed: "Удалено",
        collection_created: "Коллекция создана и синхронизирована",
        category_created: "Категория создана и синхронизирована",
        group_created: "Группа создана и синхронизирована",
        collection_removed: "Коллекция удалена",
        category_removed: "Категория удалена",
        add_to: "Добавить в",
        add_nft: "Добавить NFT",
        new_elements_updated: "NEW элементы обновлены в реальном времени",
        new_indicator_synced: "Отметка NEW синхронизирована",
        error_adding_indicator: "Ошибка добавления NEW индикатора",
        login_title: "Вход в систему",
        login_google: "Войти через Google",
        login_twitter: "Войти через Twitter",
        register: "Регистрация",
        login_btn: "Войти",
        category: "Категория",
        all_links: "Все ссылки",
        action: "Действие"
    }
};
