window.i18nData = {
    en: {
        back_to_list: "Back to List",
        full_catalog: "Complete catalog of all links and activities",
        login: "Login",
        sync_progress: "Sync your progress with the cloud",
        data_synced: "Data synced",
        logout: "Logout",
        light_theme: "Light Theme",
        dark_theme: "Dark Theme",
        light_theme_active: "Light theme active",
        dark_theme_active: "Dark theme active",
        hide_badges: "Hide Badges",
        show_badges: "Show Badges",
        badges_shown: "Badges shown",
        badges_hidden: "Badges hidden",
        edit_mode: "Edit Mode",
        finish_editing: "Finish",
        edit_mode_activated: "Edit mode activated",
        edit_mode_finished: "Edit mode finished",
        edit_mode_banner: "Edit Mode — click ✎ next to a link to modify",
        start_editing: "Start editing",
        export_json: "Export JSON",
        import_json: "Import JSON",
        upload_github: "Upload to GitHub",
        reset_progress: "Reset Progress",
        how_tracking_works: "How Tracking Works",
        hide_legend: "Hide ▾",
        show_legend: "Show ▸",
        today: "Today",
        today_desc: "Green color — action done today. After midnight the mark disappears.",
        done: "Done",
        done_desc: "Strikethrough — one-time task is closed.",
        clicks_date_desc: "Number of clicks and date.",
        new_indicator: "NEW!",
        new_desc: "Fresh links. After click the mark disappears.",
        favorites: "Favorites",
        no_favorites: "No favorite links. Click ★ next to needed ones.",
        section_faucets: "1. Get Test Tokens (Faucets)",
        section_deploy: "2. Deploy Smart Contracts",
        section_nfts: "3. Mint NFT (All Collections)",
        section_dapps: "4. dApps and Activities",
        faucets_note: "If official faucet doesn't open, try VPN or backup source.",
        basic_deploy: "Basic Deploy",
        advanced_deploy: "Advanced Deploy",
        nfts_note: "Click on NFT card to preview. Click link to mint.",
        category: "Category",
        all_links: "All Links",
        action: "Action",
        bridges: "Bridges",
        bridges_desc: "Bridge tokens to Arc network and back.",
        domains: "Domains",
        domains_desc: "Register domains in Arc network.",
        nft_dapps: "NFT dApps",
        nft_dapps_desc: "Creating your own collections.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Daily GM, Check-In, Vote transactions.",
        quests: "Quests",
        quests_desc: "Complete Layer3 quests on Arc network.",
        footer_disclaimer: "This site is an aggregator of links. DYOR.",
        data_exported: "Data exported!",
        data_imported: "Data imported!",
        error_import: "Import error",
        progress_reset: "Progress reset",
        element_added: "Element added and synced",
        element_updated: "Element updated and synced",
        go_to_mint: "Go to Mint",
        go_to_website: "Go to Website",
        new_nfts: "New NFT",
        checking: "Checking...",
        refresh: "Refresh",
        no_new_posts: "No new posts yet",
        add_item: "Add Item",
        title_label: "Title",
        url_label: "URL Link",
        tooltip_label: "Description (tooltip)",
        image_label: "Image URL (for NFT)",
        website_label: "Project Website URL",
        twitter_label: "Project Twitter URL",
        description_label: "Action Description",
        cancel: "Cancel",
        add: "Add",
        save: "Save",
        confirm_delete: "Are you sure you want to delete?",
        delete_item: "Delete item",
        delete_collection: "Delete collection",
        delete_category: "Delete category",
        removed: "Removed",
        collection_created: "Collection created and synced",
        category_created: "Category created and synced",
        group_created: "Group created and synced",
        collection_removed: "Collection removed",
        category_removed: "Category removed",
        add_to: "Add to",
        add_nft: "Add NFT",
        new_elements_updated: "NEW elements updated in real time",
        new_indicator_synced: "NEW indicator synced",
        error_adding_indicator: "Error adding NEW indicator",
        login_title: "Login to System",
        login_google: "Login with Google",
        login_twitter: "Login with Twitter",
        register: "Register",
        login_btn: "Login",
        twitter_monitor: "New NFTs",
        search_placeholder: "Search..."
    },
    ua: {
        back_to_list: "Назад до списку",
        full_catalog: "Повний каталог усіх посилань та активностей",
        login: "Увійти",
        sync_progress: "Синхронізуйте прогрес з хмарою",
        data_synced: "Дані синхронізовано",
        logout: "Вийти",
        light_theme: "Світла тема",
        dark_theme: "Темна тема",
        light_theme_active: "Світла тема активна",
        dark_theme_active: "Темна тема активна",
        hide_badges: "Сховати бейджі",
        show_badges: "Показати бейджі",
        badges_shown: "Бейджі показано",
        badges_hidden: "Бейджі сховано",
        edit_mode: "Режим редагування",
        finish_editing: "Завершити",
        edit_mode_activated: "Режим редагування активовано",
        edit_mode_finished: "Режим редагування завершено",
        edit_mode_banner: "Режим редагування — натисніть ✎ поруч зі посиланням для редагування",
        start_editing: "Почати редагування",
        export_json: "Експорт JSON",
        import_json: "Імпорт JSON",
        upload_github: "Завантажити до GitHub",
        reset_progress: "Скинути прогрес",
        how_tracking_works: "Як працює відстеження",
        hide_legend: "Сховати ▾",
        show_legend: "Показати ▸",
        today: "Сьогодні",
        today_desc: "Зелений колір — дію виконано сьогодні. Після півночі позначка зникає.",
        done: "Виконано",
        done_desc: "Перекреслено — одноразове завдання завершено.",
        clicks_date_desc: "Кількість кліків та дата останньої дії.",
        new_indicator: "НОВЕ!",
        new_desc: "Свіжі посилання. Після кліку позначка зникне.",
        favorites: "Вибране",
        no_favorites: "Немає вибраних посилань. Натисніть ★ поруч із потрібними.",
        section_faucets: "1. Отримання тестових токенів (Faucets)",
        section_deploy: "2. Деплой смарт-контрактів",
        section_nfts: "3. Мінт NFT (Усі колекції)",
        section_dapps: "4. dApps та Активності",
        faucets_note: "Якщо офіційний кран не відкривається, спробуйте VPN або резервне джерело.",
        basic_deploy: "Базовий деплой",
        advanced_deploy: "Просунутий деплой",
        nfts_note: "Натисніть на картку NFT для перегляду. Натисніть посилання для мінту.",
        category: "Категорія",
        all_links: "Усі посилання",
        action: "Дія",
        bridges: "Мости",
        bridges_desc: "Переказуйте токени в мережу Arc та назад.",
        domains: "Домени",
        domains_desc: "Зареєструйте домен у мережі Arc.",
        nft_dapps: "NFT-додатки",
        nft_dapps_desc: "Створення власних колекцій.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Щоденні транзакції GM, Check-In, Vote.",
        quests: "Квести",
        quests_desc: "Виконуйте квести Layer3 по мережі Arc.",
        footer_disclaimer: "Цей сайт є агрегатором посилань. DYOR.",
        data_exported: "Дані експортовано!",
        data_imported: "Дані імпортовано!",
        error_import: "Помилка імпорту",
        progress_reset: "Прогрес скинуто",
        element_added: "Елемент додано та синхронізовано",
        element_updated: "Елемент оновлено та синхронізовано",
        go_to_mint: "Перейти до мінту",
        go_to_website: "Перейти на сайт",
        new_nfts: "Нові NFT",
        checking: "Перевірка...",
        refresh: "Оновити",
        no_new_posts: "Нових постів поки що немає",
        add_item: "Додати елемент",
        title_label: "Назва",
        url_label: "URL посилання",
        tooltip_label: "Опис (tooltip)",
        image_label: "URL картинки (для NFT)",
        website_label: "URL сайту проєкту",
        twitter_label: "URL Twitter проєкту",
        description_label: "Опис дії",
        cancel: "Скасувати",
        add: "Додати",
        save: "Зберегти",
        confirm_delete: "Ви впевнені, що хочете видалити?",
        delete_item: "Видалити елемент",
        delete_collection: "Видалити колекцію",
        delete_category: "Видалити категорію",
        removed: "Видалено",
        collection_created: "Колекцію створено та синхронізовано",
        category_created: "Категорію створено та синхронізовано",
        group_created: "Групу створено та синхронізовано",
        collection_removed: "Колекцію видалено",
        category_removed: "Категорію видалено",
        add_to: "Додати до",
        add_nft: "Додати NFT",
        new_elements_updated: "НОВІ елементи оновлено в реальному часі",
        new_indicator_synced: "Позначку НОВЕ синхронізовано",
        error_adding_indicator: "Помилка додавання позначки НОВЕ",
        login_title: "Вхід у систему",
        login_google: "Увійти через Google",
        login_twitter: "Увійти через Twitter",
        register: "Реєстрація",
        login_btn: "Увійти",
        twitter_monitor: "Нові NFT",
        search_placeholder: "Пошук..."
    }
};
