// languages.js - Файл переводов
// Загружается автоматически вместе со страницей

window.i18nData = {
    en: {
        edit_mode_banner: "Edit Mode — click ✎ next to a link to modify",
        go_to_mint: "Go to Mint",
        go_to_website: "Go to Website",
        add_item: "Add Item",
        title_label: "Title",
        url_label: "URL Link",
        tooltip_label: "Description (tooltip)",
        image_label: "Image URL (for NFT)",
        website_label: "Project Website URL",
        twitter_label: "Project Twitter URL",
        description_label: "Action Description",
        cancel: "Cancel",
        add: "Add",
        back_to_list: "Back to List",
        login: "Login",
        sync_progress: "Sync your progress with the cloud",
        data_synced: "Data synced",
        logout: "Logout",
        new_nfts: "New NFTs",
        checking: "Checking...",
        refresh: "Refresh",
        russian: "Русский",
        light_theme: "Light Theme",
        hide_badges: "Hide Badges",
        show_badges: "Show Badges",
        edit_mode: "Edit Mode",
        export_json: "Export JSON",
        import_json: "Import JSON",
        upload_github: "Upload to GitHub",
        reset_progress: "Reset Progress",
        how_tracking_works: "How Tracking Works",
        hide_legend: "Hide ▾",
        show_legend: "Show ▸",
        today: "Today",
        today_desc: "Green color — action done today. After midnight the mark disappears.",
        done: "Done",
        done_desc: "Strikethrough — one-time task is closed.",
        clicks_date_desc: "Number of clicks and date of last action.",
        new_desc: "Fresh links. After clicking, the mark disappears.",
        full_catalog: "Complete catalog of all links and activities",
        section_faucets: "1. Get Test Tokens (Faucet)",
        faucets_note: "Here will be faucets for getting Robinhood Chain test tokens.",
        section_deploy: "2. Deploy Smart Contracts",
        basic_deploy: "Basic Deploy",
        advanced_deploy: "Advanced Deploy",
        section_nfts: "3. Mint NFT (All Collections)",
        nfts_note: "Below are direct mint links. Click to mark as completed.",
        section_dapps: "4. dApps and Activities",
        category: "Category",
        all_links: "All Links",
        action: "Action",
        bridges: "Bridges",
        bridges_desc: "Send tokens to and from the network.",
        domains: "Domains",
        domains_desc: "Register domains.",
        nft_dapps: "NFT dApps",
        nft_dapps_desc: "Marketplaces and tools.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Daily transactions.",
        footer_disclaimer: "This site is an aggregator of links. DYOR.",
        favorites: "Favorites",
        no_favorites: "No favorite links. Click ★ next to needed ones.",
        light_theme_active: "Light theme active",
        dark_theme_active: "Dark theme active",
        badges_hidden: "Badges hidden",
        badges_shown: "Badges shown",
        edit_mode_activated: "Edit mode activated. Click ✎ next to a link to modify.",
        edit_mode_finished: "Edit mode finished",
        progress_reset: "Progress reset",
        data_exported: "Data exported!",
        data_imported: "Data imported! Reloading...",
        error_import: "Import error",
        element_added: "Element added and synced",
        element_updated: "Element updated and synced",
        collection_created: "Collection created",
        category_created: "Category created",
        group_created: "Group created",
        removed: "Removed",
        collection_removed: "Collection removed",
        category_removed: "Category removed",
        group_removed: "Group removed",
        new_indicator_synced: "🔄 NEW indicator synced",
        new_elements_updated: "🔄 NEW elements updated in real time",
        error_adding_indicator: "❌ Error adding NEW indicator",
        start_editing: "Start editing",
        finish_editing: "Finish editing",
        new_indicator: "NEW!",
        save: "Save",
        delete_collection: "Delete collection",
        delete_category: "Delete category",
        delete_item: "Delete item",
        confirm_delete: "Are you sure?",
        delete_title: "Delete",
        add_nft: "Add NFT",
        add_to: "Add to",
        login_title: "Login to System",
        login_google: "Login with Google",
        login_twitter: "Login with Twitter",
        register: "Register",
        login_btn: "Login"
    },
    ru: {
        edit_mode_banner: "Режим редактирования — нажмите ✎ рядом со ссылкой для изменения",
        go_to_mint: "Перейти к минту",
        go_to_website: "Перейти на Website",
        add_item: "Добавить элемент",
        title_label: "Название",
        url_label: "URL ссылки",
        tooltip_label: "Описание (tooltip)",
        image_label: "URL картинки (для NFT)",
        website_label: "URL сайта проекта",
        twitter_label: "URL Twitter проекта",
        description_label: "Описание действия",
        cancel: "Отмена",
        add: "Добавить",
        back_to_list: "Назад к списку",
        login: "Войти",
        sync_progress: "Синхронизируйте прогресс с облаком",
        data_synced: "Данные синхронизированы",
        logout: "Выйти",
        new_nfts: "Новые NFT",
        checking: "Проверка...",
        refresh: "Обновить",
        russian: "English",
        light_theme: "Светлая тема",
        hide_badges: "Скрыть бейджи",
        show_badges: "Показать бейджи",
        edit_mode: "Режим редактирования",
        export_json: "Экспорт JSON",
        import_json: "Импорт JSON",
        upload_github: "Загрузить на GitHub",
        reset_progress: "Сбросить прогресс",
        how_tracking_works: "Как работает отслеживание",
        hide_legend: "Скрыть инструкцию ▾",
        show_legend: "Показать инструкцию ▸",
        today: "Сегодня",
        today_desc: "Зелёный цвет — действие выполнено сегодня. После полуночи отметка исчезает.",
        done: "Выполнено",
        done_desc: "Зачёркнуто — одноразовая задача закрыта.",
        clicks_date_desc: "Количество кликов и дата последнего действия.",
        new_desc: "Свежие ссылки. После клика метка пропадёт.",
        full_catalog: "Полный каталог всех ссылок и активностей",
        section_faucets: "1. Получение тестовых токенов (Faucet)",
        faucets_note: "Здесь будут краны для получения тестовых токенов Robinhood Chain.",
        section_deploy: "2. Деплой смарт-контрактов",
        basic_deploy: "Базовый деплой",
        advanced_deploy: "Продвинутый деплой",
        section_nfts: "3. Минт NFT (Все коллекции)",
        nfts_note: "Ниже — прямые ссылки на минт. Нажмите, чтобы отметить выполненное.",
        section_dapps: "4. dApps и Активности",
        category: "Категория",
        all_links: "Все ссылки",
        action: "Действие",
        bridges: "Мосты (Bridges)",
        bridges_desc: "Отправляйте токены в сеть и обратно.",
        domains: "Domains",
        domains_desc: "Регистрация доменов.",
        nft_dapps: "NFT dApps",
        nft_dapps_desc: "Маркетплейсы и инструменты.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Ежедневные транзакции.",
        footer_disclaimer: "Данный сайт является агрегатором ссылок. DYOR.",
        favorites: "Избранное",
        no_favorites: "Нет избранных ссылок. Нажмите ★ рядом с нужными.",
        light_theme_active: "Светлая тема активна",
        dark_theme_active: "Тёмная тема активна",
        badges_hidden: "Бейджи скрыты",
        badges_shown: "Бейджи показаны",
        edit_mode_activated: "Режим редактирования активирован. Нажмите ✎ рядом со ссылкой для изменения.",
        edit_mode_finished: "Редактирование завершено",
        progress_reset: "Прогресс сброшен",
        data_exported: "Данные экспортированы!",
        data_imported: "Данные импортированы! Страница обновится.",
        error_import: "Ошибка импорта",
        element_added: "Элемент добавлен и синхронизирован",
        element_updated: "Элемент обновлён и синхронизирован",
        collection_created: "Коллекция создана",
        category_created: "Категория создана",
        group_created: "Группа создана",
        removed: "Удалено",
        collection_removed: "Коллекция удалена",
        category_removed: "Категория удалена",
        group_removed: "Группа удалена",
        new_indicator_synced: "🔄 Отметка NEW синхронизирована",
        new_elements_updated: "🔄 NEW элементы обновлены в реальном времени",
        error_adding_indicator: "❌ Ошибка добавления NEW индикатора",
        start_editing: "Начать редактирование",
        finish_editing: "Завершить редактирование",
        new_indicator: "NEW!",
        save: "Сохранить",
        delete_collection: "Удалить коллекцию",
        delete_category: "Удалить категорию",
        delete_item: "Удалить элемент",
        cancel_sure: "Отмена",
        confirm_delete: "Вы уверены?",
        delete_title: "Удалить",
        add_nft: "Добавить NFT",
        add_to: "Добавить в",
        login_title: "Вход в систему",
        login_google: "Войти через Google",
        login_twitter: "Войти через Twitter",
        register: "Регистрация",
        login_btn: "Войти"
    }
};

window.i18nDataLoaded = true;
