// languages.js - Файл переводов
// Загружается автоматически вместе со страницей

window.i18nData = {
    en: {
        edit_mode_banner: "Edit Mode — click ✎ next to a link to modify",
        go_to_mint: "Go to Mint",
        go_to_website: "Go to Website",
        add_item: "Add Item",
        title_label: "Title",
        url_label: "URL Link",
        tooltip_label: "Description (tooltip)",
        image_label: "Image URL (for NFT)",
        website_label: "Project Website URL",
        twitter_label: "Project Twitter URL",
        description_label: "Action Description",
        cancel: "Cancel",
        add: "Add",
        back_to_list: "Back to List",
        login: "Login",
        sync_progress: "Sync your progress with the cloud",
        data_synced: "Data synced",
        logout: "Logout",
        new_nfts: "New NFTs",
        checking: "Checking...",
        refresh: "Refresh",
        ukrainian: "Українська",
        light_theme: "Light Theme",
        hide_badges: "Hide Badges",
        show_badges: "Show Badges",
        edit_mode: "Edit Mode",
        export_json: "Export JSON",
        import_json: "Import JSON",
        upload_github: "Upload to GitHub",
        reset_progress: "Reset Progress",
        how_tracking_works: "How Tracking Works",
        hide_legend: "Hide ▾",
        show_legend: "Show ▸",
        today: "Today",
        today_desc: "Green color — action done today. After midnight the mark disappears.",
        done: "Done",
        done_desc: "Strikethrough — one-time task is closed.",
        clicks_date_desc: "Number of clicks and date of last action.",
        new_desc: "Fresh links. After clicking, the mark disappears.",
        full_catalog: "Complete catalog of all links and activities",
        section_faucets: "1. Get Test Tokens (Faucet)",
        faucets_note: "Here will be faucets for getting Robinhood Chain test tokens.",
        section_deploy: "2. Deploy Smart Contracts",
        basic_deploy: "Basic Deploy",
        advanced_deploy: "Advanced Deploy",
        section_nfts: "3. Mint NFT (All Collections)",
        nfts_note: "Below are direct mint links. Click to mark as completed.",
        section_dapps: "4. dApps and Activities",
        category: "Category",
        all_links: "All Links",
        action: "Action",
        bridges: "Bridges",
        bridges_desc: "Send tokens to and from the network.",
        domains: "Domains",
        domains_desc: "Register domains.",
        nft_dapps: "NFT dApps",
        nft_dapps_desc: "Marketplaces and tools.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Daily transactions.",
        footer_disclaimer: "This site is an aggregator of links. DYOR.",
        favorites: "Favorites",
        no_favorites: "No favorite links. Click ★ next to needed ones.",
        light_theme_active: "Light theme active",
        dark_theme_active: "Dark theme active",
        badges_hidden: "Badges hidden",
        badges_shown: "Badges shown",
        edit_mode_activated: "Edit mode activated. Click ✎ next to a link to modify.",
        edit_mode_finished: "Edit mode finished",
        progress_reset: "Progress reset",
        data_exported: "Data exported!",
        data_imported: "Data imported! Reloading...",
        error_import: "Import error",
        element_added: "Element added and synced",
        element_updated: "Element updated and synced",
        collection_created: "Collection created",
        category_created: "Category created",
        group_created: "Group created",
        removed: "Removed",
        collection_removed: "Collection removed",
        category_removed: "Category removed",
        group_removed: "Group removed",
        new_indicator_synced: "🔄 NEW indicator synced",
        new_elements_updated: "🔄 NEW elements updated in real time",
        error_adding_indicator: "❌ Error adding NEW indicator",
        start_editing: "Start editing",
        finish_editing: "Finish editing",
        new_indicator: "NEW!",
        save: "Save",
        delete_collection: "Delete collection",
        delete_category: "Delete category",
        delete_item: "Delete item",
        confirm_delete: "Are you sure?",
        delete_title: "Delete",
        add_nft: "Add NFT",
        add_to: "Add to",
        login_title: "Login to System",
        login_google: "Login with Google",
        login_twitter: "Login with Twitter",
        register: "Register",
        login_btn: "Login"
    },
    ua: {
        edit_mode_banner: "Режим редагування — натисніть ✎ поруч з посиланням для зміни",
        go_to_mint: "Перейти до мінту",
        go_to_website: "Перейти на Website",
        add_item: "Додати елемент",
        title_label: "Назва",
        url_label: "URL посилання",
        tooltip_label: "Опис (tooltip)",
        image_label: "URL картинки (для NFT)",
        website_label: "URL сайту проекту",
        twitter_label: "URL Twitter проекту",
        description_label: "Опис дії",
        cancel: "Скасувати",
        add: "Додати",
        back_to_list: "Назад до списку",
        login: "Увійти",
        sync_progress: "Синхронізуйте прогрес з хмарою",
        data_synced: "Дані синхронізовано",
        logout: "Вийти",
        new_nfts: "Нові NFT",
        checking: "Перевірка...",
        refresh: "Оновити",
        ukrainian: "English",
        light_theme: "Світла тема",
        hide_badges: "Приховати бейджі",
        show_badges: "Показати бейджі",
        edit_mode: "Режим редагування",
        export_json: "Експорт JSON",
        import_json: "Імпорт JSON",
        upload_github: "Завантажити на GitHub",
        reset_progress: "Скинути прогрес",
        how_tracking_works: "Як працює відстеження",
        hide_legend: "Приховати інструкцію ▾",
        show_legend: "Показати інструкцію ▸",
        today: "Сьогодні",
        today_desc: "Зелений колір — дію виконано сьогодні. Після опівночі позначка зникає.",
        done: "Виконано",
        done_desc: "Закреслено — одноразове завдання закрито.",
        clicks_date_desc: "Кількість кліків і дата останньої дії.",
        new_desc: "Свіжі посилання. Після кліку мітка зникне.",
        full_catalog: "Повний каталог всіх посилань та активностей",
        section_faucets: "1. Отримання тестових токенів (Faucet)",
        faucets_note: "Тут будуть крани для отримання тестових токенів Robinhood Chain.",
        section_deploy: "2. Деплой смарт-контрактів",
        basic_deploy: "Базовий деплой",
        advanced_deploy: "Просунутий деплой",
        section_nfts: "3. Мінт NFT (Всі колекції)",
        nfts_note: "Нижче — прямі посилання на мінт. Натисніть, щоб відмітити виконане.",
        section_dapps: "4. dApps та Активності",
        category: "Категорія",
        all_links: "Всі посилання",
        action: "Дія",
        bridges: "Мости (Bridges)",
        bridges_desc: "Відправляйте токени в мережу і назад.",
        domains: "Domains",
        domains_desc: "Реєстрація доменів.",
        nft_dapps: "NFT dApps",
        nft_dapps_desc: "Маркетплейси та інструменти.",
        checkin_daily: "Check-In & Daily",
        checkin_desc: "Щоденні транзакції.",
        footer_disclaimer: "Даний сайт є агрегатором посилань. DYOR.",
        favorites: "Вибране",
        no_favorites: "Немає вибраних посилань. Натисніть ★ поруч з потрібними.",
        light_theme_active: "Світла тема активна",
        dark_theme_active: "Темна тема активна",
        badges_hidden: "Бейджі приховано",
        badges_shown: "Бейджі показано",
        edit_mode_activated: "Режим редагування активовано. Натисніть ✎ поруч з посиланням для зміни.",
        edit_mode_finished: "Редагування завершено",
        progress_reset: "Прогрес скинуто",
        data_exported: "Дані експортовано!",
        data_imported: "Дані імпортовано! Сторінка оновиться.",
        error_import: "Помилка імпорту",
        element_added: "Елемент додано та синхронізовано",
        element_updated: "Елемент оновлено та синхронізовано",
        collection_created: "Колекцію створено",
        category_created: "Категорію створено",
        group_created: "Групу створено",
        removed: "Видалено",
        collection_removed: "Колекцію видалено",
        category_removed: "Категорію видалено",
        group_removed: "Групу видалено",
        new_indicator_synced: "🔄 Позначку NEW синхронізовано",
        new_elements_updated: "🔄 NEW елементи оновлено в реальному часі",
        error_adding_indicator: "❌ Помилка додавання NEW індикатора",
        start_editing: "Почати редагування",
        finish_editing: "Завершити редагування",
        new_indicator: "NEW!",
        save: "Зберегти",
        delete_collection: "Видалити колекцію",
        delete_category: "Видалити категорію",
        delete_item: "Видалити елемент",
        cancel_sure: "Скасувати",
        confirm_delete: "Ви впевнені?",
        delete_title: "Видалити",
        add_nft: "Додати NFT",
        add_to: "Додати до",
        login_title: "Вхід у систему",
        login_google: "Увійти через Google",
        login_twitter: "Увійти через Twitter",
        register: "Реєстрація",
        login_btn: "Увійти"
    }
};

window.i18nDataLoaded = true;
